### ISSUE TITLE
Document required Ruby version to run the docs or add support for latest Ruby versions

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/docs-book-cloudfoundry#110]
I tried to run the bookbinder with my local changes following the description in [contributing-pull-requests](https://github.com/cloudfoundry/docs-book-cloudfoundry#contributing-pull-requests) using Ruby 2.7.0 and it failed with:
```
bundle exec bookbinder watch
Traceback (most recent call last):
	23: from /Users/<user>/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `<main>'
	22: from /Users/<user>/.rvm/gems/ruby-2.7.0/bin/ruby_executable_hooks:22:in `eval'
	21: from /Users/<user>/.rvm/gems/ruby-2.7.0/bin/bookbinder:23:in `<main>'
	20: from /Users/<user>/.rvm/gems/ruby-2.7.0/bin/bookbinder:23:in `load'
	19: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/install_bin/bookbinder:3:in `<top (required)>'
	18: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/install_bin/bookbinder:3:in `require_relative'
	17: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/cli.rb:6:in `<top (required)>'
	16: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/cli.rb:6:in `require_relative'
	15: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/commands/collection.rb:21:in `<top (required)>'
	14: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/commands/collection.rb:21:in `require_relative'
	13: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/preprocessing/dita_html_preprocessor.rb:2:in `<top (required)>'
	12: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/preprocessing/dita_html_preprocessor.rb:2:in `require_relative'
	11: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/subnav/navigation_entries_from_html_toc.rb:2:in `<top (required)>'
	10: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/bookbindery-9.12.1/lib/bookbinder/subnav/navigation_entries_from_html_toc.rb:2:in `require'
	 9: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/all.rb:3:in `<top (required)>'
	 8: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/all.rb:3:in `require'
	 7: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:1:in `<top (required)>'
	 6: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:1:in `each'
	 5: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
	 4: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext.rb:2:in `require'
	 3: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object.rb:3:in `<top (required)>'
	 2: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object.rb:3:in `require'
	 1: from /Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:106:in `<top (required)>'
/Users/<user>/.rvm/gems/ruby-2.7.0/gems/activesupport-4.2.11.1/lib/active_support/core_ext/object/duplicable.rb:111:in `<class:BigDecimal>': undefined method `new' for BigDecimal:Class (NoMethodError)

```
With Ruby `2.6.5` it worked. Will be great to document the supported Ruby versions to run the bookbinder or add support for the latest Ruby version like `2.7.0` or `3.0.0`. I couldn't find any hints which Ruby version should I use.

**Comment by paigecalvert** [comment]
Thanks @beyhan, this is a great note. To provide a little context: we don't currently have any engineering support maintaining this bookbinder instance. So, while adding support for the latest Ruby versions is on our wish-list, it's not likely to get prioritized until we have someone with the right skill set can pick up that work.

And I'm glad to hear that 2.6.5 worked for you. (That actually surprises me, I thought that we didn't have support beyond 2.5.5). As my surprise in my previous comment suggests, I'm probably not the most qualified person to provide a _definitive_ list of supported Ruby versions :D. Though, a "hint" would certainly be possible. I'll work on asking around to see about including that info.

Thanks again

**Comment by animatedmax** [comment]
Hi @beyhan We've added the list of Ruby versions that Bookbinder was tested on to https://github.com/cloudfoundry/docs-book-cloudfoundry/blob/master/README.md. Thanks!
